CREATE DATABASE IF NOT EXISTS lab1_db;
CREATE DATABASE IF NOT EXISTS lab2_db;
CREATE DATABASE IF NOT EXISTS z12_db;

USE lab1_db;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

USE lab2_db;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

USE z12_db;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pomiary (
    id INT AUTO_INCREMENT PRIMARY KEY,
    x1 FLOAT NOT NULL,
    x2 FLOAT NOT NULL,
    x3 FLOAT NOT NULL,
    x4 FLOAT NOT NULL,
    x5 FLOAT NOT NULL,
    pozar TINYINT(1) DEFAULT 0,
    zalanie TINYINT(1) DEFAULT 0,
    wentylacja TINYINT(1) DEFAULT 0,
    datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
